apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-management
  namespace: real-estate-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-estate-management
  template:
    metadata:
      labels:
        app: real-estate-management
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: real-estate-management
          image: ghcr.io/mohsinfiroz/real-estate-management:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_SSL_MODE

---
apiVersion: v1
kind: Service
metadata:
  name: real-estate-management
  namespace: real-estate-prod
spec:
  selector:
    app: real-estate-management
  ports:
    - protocol: TCP
      port: 80    # External port
      targetPort: 8080   # Container port
  type: NodePort  # Change to NodePort if needed

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-estate-ingress
  namespace: real-estate-prod
spec:
  rules:
    - host: real-estate.softcelia.com  # Change to your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: real-estate-management
                port:
                  number: 80
