server {
    listen 80;
    server_name db.softcelia.com;
    
    location / {
        proxy_pass http://localhost:5432;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}