name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Or any other branch you want to deploy on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.6'

    # Set up kubectl to interact with your Kubernetes cluster
    - name: Set up kubectl
      run: |
        # Install kubectl
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # Create .kube directory and authenticate to OVH Kubernetes cluster
    - name: Authenticate to OVH Kubernetes cluster
      run: |
        mkdir -p $HOME/.kube  # Create .kube directory if it doesn't exist
        echo "${{ secrets.OVH_KUBECONFIG }}" > $HOME/.kube/config  # Write kubeconfig

    # Set up GitHub authentication using GitHub's token to access the registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to access the container registry

    # Apply Kubernetes Secret for GHCR (create or update)
    - name: Apply Kubernetes Secret for GHCR
      run: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: ghcr-secret
          namespace: real-estate-prod
        type: Opaque
        data:
          .dockerconfigjson: $(echo -n '{"auths":{"ghcr.io":{"username":"'"${{ github.actor }}"'","password":"'"${{ secrets.GITHUB_TOKEN }}"'"}}}' | base64)
        EOF

    # Apply Kubernetes Secret for PostgreSQL credentials (create or update)
    - name: Apply Kubernetes Secret for PostgreSQL
      run: |
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: db-secret
          namespace: real-estate-prod
        type: Opaque
        data:
          DB_HOST: $(echo -n "postgresql-service.real-estate-prod.svc.cluster.local" | base64)
          DB_PORT: $(echo -n "5432" | base64)
          DB_USER: $(echo -n "${{ secrets.DB_USER }}" | base64)
          DB_PASSWORD: $(echo -n "${{ secrets.DB_PASSWORD }}" | base64)
          DB_NAME: $(echo -n "${{ secrets.DB_NAME }}" | base64)
          DB_SSL_MODE: $(echo -n "${{ secrets.DB_SSL_MODE }}" | base64)
        EOF

    # Deploy PostgreSQL to Kubernetes
    - name: Deploy PostgreSQL to Kubernetes
      run: |
        kubectl apply -f k8s/postgresql.yaml
        kubectl rollout status deployment/postgresql -n real-estate-prod

    # Deploy Go Application to Kubernetes
    - name: Deploy Go Application to Kubernetes
      run: |
        kubectl apply -f k8s/app.yaml
        kubectl rollout status deployment/real-estate-management -n real-estate-prod
